exam/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  url(r'^$', views.index, name='index'),
                  url(r'^(?P<exam_id>[0-9]+)/passe/$', views.passe, name='passe_exam'),
                  url(r'^(?P<exam_id>[0-9]+)/mode/$', views.mode, name='mode_exam'),
                  url(r'^(?P<exam_id>[0-9]+)/$', views.detail, name='detail'),
                  url(r'^(?P<exam_id>[0-9]+)/reponse/$', views.reponse, name='reponse'),
                  url(r'^(?P<exam_id>[0-9]+)/edit/$', views.edit, name='edit'),
                  url(r'^(?P<Quest_id>[0-9]+)/editfree/$', views.editfree, name='editfree'),
                  url(r'^(?P<Quest_id>[0-9]+)/editmulti/$', views.editmulti, name='editmulti'),
                  url(r'^(?P<Quest_id>[0-9]+)/editone/$', views.editone, name='editone'),
                  url(r'^create/$', views.create_view, name='create_view'),
                  url(r'^createQuest/$', views.createExam, name='createExam'),
                  url(r'^secondeQuest/$', views.secondeQuest, name='secondeQuest'),
                  url(r'^(?P<exam_id>[0-9]+)/addQuest/$', views.addQuest, name='addQuest'),
                  url(r'^(?P<exam_id>[0-9]+)/deleteEXam/$', views.deleteEXam, name='deleteEXam'),
                  url(r'^(?P<question_id>[0-9]+)/deleteQuest/$', views.deleteQuest, name='deleteQuest'),
                  url(r'^(?P<exam_id>[0-9]+)/edit/$', views.edit, name='edit'),
                  url(r'^(?P<pk>[0-9]+)/assigne_student/$', views.assigne_classroom, name='assigne_classroom'),
                  url(r'^(?P<pk>[0-9]+)/add/(?P<selected_id>[0-9]+)/to_yard/$', views.add_to_yard, name='add_to_yard'),
                  url(r'^(?P<examen_id>[0-9]+)/(?P<score>[0-9]+)/$', views.certif, name='certif'),
                  url(r'^(?P<pk>[0-9]+)/addStudent/$', views.addStudent, name='addStudent'),
                  url(r'^(?P<exam_id>[0-9]+)/passe/(?P<Quest_id>[0-9]+)$', views.passeQuest, name='passeQuest'),
                  url(r'^(?P<exam_id>[0-9]+)/result/$', views.result, name='result'),
                  url(r'^sendmail/$', views.sendmail, name='sendemail'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quizz/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('Authentification.urls')),
    url(r'^dashboard/', include('Dashboard.urls')),
    url(r'^users/', include('users.urls')),
    url(r'^exam/', include('exam.urls')),

]

exam/models.py
from django.db import models
# from django.contrib.auth.models import User
from Authentification.models import UserP, UserS
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.shortcuts import render, redirect, render_to_response
from django.contrib import messages


# Create your models here.

class Exam(models.Model):
    MODE = (('TT', 'Training_Timer'),
            ('T', 'Training'),
            ('OC', 'One_try_certifie'),
            ('O', 'One_try'),
            )
    name = models.CharField(max_length=50)
    logo = models.ImageField(upload_to='exam_image', blank=True)
    description = models.CharField(max_length=50)
    category = models.CharField(max_length=50, default='')
    score = models.IntegerField(default=0)
    timer = models.IntegerField(default=0)
    mode = models.CharField(max_length=2, choices=MODE, blank=True, null=True)
    tryed = models.BooleanField(default=False, blank=True)

    def __str__(self):
        return self.name

#
# @receiver(post_save, sender=Exam)
# def finished(sender, **kwargs):
#     exam = kwargs.get('instance')
#     print(exam.name)
#     messages.add_message(request, messages.INFO, 'exam finished')
#
#     return render_to_response('exam/notification.html')


class Question(models.Model):
    examen = models.ForeignKey(Exam, on_delete=models.CASCADE)
    description = models.CharField(max_length=1000, default='')
    points = models.IntegerField(default=0)
    header_text = models.CharField(max_length=1000, default='')
    footer_text = models.CharField(max_length=1000, default='')
    success_msg = models.CharField(max_length=1000, default='')
    fail_msg = models.CharField(max_length=1000, default='')
    explanation = models.CharField(max_length=1000, default='', blank=True, null=True)
    correct = models.CharField(max_length=1000, default='', blank=True, null=True)

    def __str__(self):
        return self.description


class one_answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_variant = models.CharField(max_length=50)
    answer_description = models.CharField(max_length=1000)
    points = models.IntegerField(default=0)

    def __str__(self):
        return self.answer_variant


class Multi_choice_answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    multi_variant = models.CharField(max_length=50)
    multi_description = models.CharField(max_length=1000)
    points = models.IntegerField(default=0)

    def __str__(self):
        return self.multi_variant


class Free_text(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=1000)
    correct = models.CharField(max_length=1000, blank=True, null=True)

    def __str__(self):
        return self.text


class Reponse(models.Model):
    userS = models.ForeignKey(UserS, on_delete=models.CASCADE, blank=True, null=True)
    userP = models.ForeignKey(UserP, on_delete=models.CASCADE, blank=True, null=True)
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE, related_name='Exam', default=1)
    One_answer = models.ForeignKey(one_answer, on_delete=models.CASCADE, related_name='One_answer', blank=True,
                                   null=True)
    multi_choice_answer = models.ForeignKey(Multi_choice_answer, on_delete=models.CASCADE,
                                            related_name='multi_choice_answer', blank=True, null=True)
    free_text = models.CharField(max_length=1000, default='', blank=True,
                                 null=True)  # enregistrer le score ou l id!!!!!!!!!
    score_question = models.IntegerField(default=0)


# class Yard(models.Model):
# 	professor=models.ForeignKey(Profesoor,on_delete=models.CASCADE)
# 	exam=models.ForeignKey(Exam,on_delete=models.CASCADE)


class Notification(models.Model):
    title = models.CharField(max_length=256)
    text = models.TextField()
    viewed = models.BooleanField(default=False)
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE, related_name='notified_exam')

exam/views.py
from django.core.mail import send_mail
from django.shortcuts import render, redirect, render_to_response
from Dashboard.models import Yard
from .models import Question, Exam, one_answer, Free_text, Multi_choice_answer, Reponse
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.template import loader
from random import *
import datetime
from Authentification.models import UserP, UserS
from django.contrib import messages
from django.contrib import messages
from django.db.models.signals import post_save
from django.dispatch import receiver


@receiver(post_save, sender=Exam)
def finished(sender, **kwargs):
    exam = kwargs.get('instance')
    print(exam.name)
    # messages.add_message(request, messages.INFO, 'exam finished')
    pass

def index(request):
    if 'id' in request.session:
        all_exam = Exam.objects.all()
        template = loader.get_template('exam/index.html')
        context = {
            'all_exam': all_exam,
        }
        return HttpResponse(template.render(context, request))


def edit(request, exam_id):
    if not request.session['is_prof']:
        return redirect("/exam/")
    if request.session['is_prof'] is True:
        exam = Exam.objects.get(pk=exam_id)
        if request.method == "POST":
            examName = request.POST['examName']
            ExamDesc = request.POST['ExamDesc']
            category = request.POST['category']
            logo = request.FILES['logo']

            exam.name = examName
            exam.description = ExamDesc
            exam.category = category
            exam.logo = logo
            exam.save()
            return redirect('/exam/')
        template = loader.get_template('exam/edit.html')
        context = {
            'examen_id': exam_id,
            'examen': exam,

        }

        return HttpResponse(template.render(context, request))


def detail(request, exam_id):
    if request.session['is_prof'] == False:
        return redirect("/exam/")
    if request.session['is_prof'] is True:
        exam = Exam.objects.get(pk=exam_id)
        template = loader.get_template('exam/les_questions.html')
        context = {
            'examen_id': exam_id,
            'examen': exam,

        }

        return HttpResponse(template.render(context, request))


def editone(request, Quest_id):
    if not request.session['is_prof']:
        return redirect("/exam/")
    if request.session['is_prof'] is True:
        question = Question.objects.get(pk=Quest_id)
        if 'id' in request.session:
            if request.method == 'POST':
                Description = request.POST['Description']
                Header_text = request.POST['Header_text']
                Footer_text = request.POST['Footer_text']
                Success_msg = request.POST['Success_msg']
                Fail_msg = request.POST['Fail_msg']
                points = request.POST['points']
                question.description = Description
                question.header_text = Header_text
                question.footer_text = Footer_text
                question.success_msg = Success_msg
                question.fail_msg = Fail_msg
                question.points = points
                question.save()
                ID1 = request.POST['id1']
                ID2 = request.POST['id2']
                ID3 = request.POST['id3']
                ans1 = one_answer.objects.get(pk=ID1)
                ans2 = one_answer.objects.get(pk=ID2)
                ans3 = one_answer.objects.get(pk=ID3)

                answer_variant = request.POST['answer_variant1']
                answer_description = request.POST['answer_description1']
                pointsAns = request.POST['points1']
                answer_variant2 = request.POST['answer_variant2']
                answer_description2 = request.POST['answer_description2']
                pointsAns2 = request.POST['points2']
                answer_variant3 = request.POST['answer_variant3']
                answer_descriptio3 = request.POST['answer_description3']
                pointsAn3 = request.POST['points3']

                ans1.answer_variant = answer_variant
                ans1.answer_description = answer_description
                ans1.points = pointsAns
                ans1.save()
                ans2.answer_variant = answer_variant2
                ans2.answer_description = answer_description2
                ans2.points = pointsAns2
                ans2.save()
                ans3.answer_variant = answer_variant3
                ans3.answer_description = answer_descriptio3
                ans3.points = pointsAn3
                ans3.save()

                return redirect("/exam/")
            else:
                template = loader.get_template('exam/editOneAnser.html')
                context = {
                    'question': question,

                }

                return HttpResponse(template.render(context, request))


def editmulti(request, Quest_id):
    if request.session['is_prof'] == False:
        return redirect("/exam/")
    if request.session['is_prof'] is True:
        question = Question.objects.get(pk=Quest_id)
        if 'id' in request.session:
            if request.method == 'POST':
                Description = request.POST['Description']
                Header_text = request.POST['Header_text']
                Footer_text = request.POST['Footer_text']
                Success_msg = request.POST['Success_msg']
                Fail_msg = request.POST['Fail_msg']
                points = request.POST['points']
                question.description = Description
                question.header_text = Header_text
                question.footer_text = Footer_text
                question.success_msg = Success_msg
                question.fail_msg = Fail_msg
                question.points = points
                question.save()
                ID1 = request.POST['id1']
                ID2 = request.POST['id2']
                ID3 = request.POST['id3']
                ans1 = Multi_choice_answer.objects.get(pk=ID1)
                ans2 = Multi_choice_answer.objects.get(pk=ID2)
                ans3 = Multi_choice_answer.objects.get(pk=ID3)

                answer_variant = request.POST['answer_variant1']
                answer_description = request.POST['answer_description1']
                pointsAns = request.POST['points1']
                answer_variant2 = request.POST['answer_variant2']
                answer_description2 = request.POST['answer_description2']
                pointsAns2 = request.POST['points2']
                answer_variant3 = request.POST['answer_variant3']
                answer_descriptio3 = request.POST['answer_description3']
                pointsAn3 = request.POST['points3']

                ans1.multi_variant = answer_variant
                ans1.multi_description = answer_description
                ans1.points = pointsAns
                ans1.save()
                ans2.multi_variant = answer_variant2
                ans2.multi_description = answer_description2
                ans2.points = pointsAns2
                ans2.save()
                ans3.multi_variant = answer_variant3
                ans3.multi_description = answer_descriptio3
                ans3.points = pointsAn3
                ans3.save()

                return redirect("/exam/")
            else:
                template = loader.get_template('exam/EditMulti.html')
                context = {
                    'question': question,

                }

                return HttpResponse(template.render(context, request))


def editfree(request, Quest_id):
    if request.session['is_prof'] == False:
        return redirect("/exam/")
    if request.session['is_prof'] is True:
        question = Question.objects.get(pk=Quest_id)
        if 'id' in request.session:
            if request.method == 'POST':
                Description = request.POST['Description']
                Header_text = request.POST['Header_text']
                Footer_text = request.POST['Footer_text']
                Success_msg = request.POST['Success_msg']
                Fail_msg = request.POST['Fail_msg']
                points = request.POST['points']
                question.description = Description
                question.header_text = Header_text
                question.footer_text = Footer_text
                question.success_msg = Success_msg
                question.fail_msg = Fail_msg
                question.points = points
                question.save()
                id = request.POST['id']
                freeText = Free_text.objects.get(pk=id)
                text = request.POST['text']
                freeText.text = text
                freeText.save()
                return redirect("/exam/")
            else:
                template = loader.get_template('exam/EditFreeText.html')
                context = {
                    'question': question,

                }

                return HttpResponse(template.render(context, request))


def reponse(request, exam_id):
    exam = Exam.objects.get(pk=exam_id)
    template = loader.get_template('exam/valider.html')

    try:
        choice = one_answer.objects.get(pk=request.POST['choice'])


    except(KeyError):

        exam.total = 0
        exam.save()
        context = {
            'exam': exam,
            'exam_id': exam_id,
            'message': 'choix non valide',

        }
        return HttpResponse(template.render(context, request))
    else:
        exam.total = choice.note
        exam.save()
        context = {
            'exam': exam,
            'exam_id': exam_id,

        }
        return HttpResponse(template.render(context, request))


def create_view(request):
    if 'id' in request.session:
        return render(request, 'exam/createExam.html')


def createExam(request):
    if request.session['is_prof'] == False:
        return redirect("/exam/")

exam/templates/exam/EditFreeText.html
    {% extends "base.html" %}

    {% block title %}Login{% endblock %}

    {% block content %}
        <!-- Page Content -->
        <div class="container">
<form method="post" action="">
          <!-- Page Heading -->

                        <div class="col-xs-12 col-sm-12">
                                 {%csrf_token%}
                            <div class="card">
                                <div class="card-header">
                                    <div class="col-lg-6 ">
                                    <strong>Create Question</strong></div>
                                </div>
                                <div class="card-body card-block">
                                    <div class="form-group">
                                        <label class=" form-control-label">Description: :</label>
                                        <div class="input-group">
                                            <div class="input-group-addon"></div>
                                            <input class="form-control" value="{{question.description}}" name="Description">
                                        </div>
                                        <small class="form-text text-muted"></small>
                                    </div>
                                    <div class="form-group">
                                        <label class=" form-control-label">Header text</label>
                                        <div class="input-group">
                                            <div class="input-group-addon"></div>
                                            <input class="form-control" value="{{question.header_text}}" name="Header_text">
                                        </div>

                                    </div>
                                    <div class="form-group">
                                        <label class=" form-control-label">Footer text</label>
                                        <div class="input-group">
                                            <div class="input-group-addon"></div>
                                            <input class="form-control"value="{{question.footer_text}}" name="Footer_text">
                                        </div>

                                    </div>

                                    <div class="form-group">
                                        <label class=" form-control-label">Success msg</label>
                                        <div class="input-group">
                                            <div class="input-group-addon"></div>
                                            <input class="form-control" value="{{question.success_msg}}" name="Success_msg">
                                        </div>

                                    </div>
                                    <div class="form-group">
                                        <label class=" form-control-label">fail msg</label>
                                        <div class="input-group">
                                            <div class="input-group-addon"></div>
                                            <input class="form-control" value="{{question.fail_msg}}"  name="Fail_msg">
                                        </div>

                                    </div>
                                    <div class="form-group">
                                        <label class=" form-control-label">points</label>
                                        <div class="input-group">
                                            <div class="input-group-addon"></div>
                                            <input class="form-control" type="number" value="{{question.points}}"  name="points">
                                        </div>

                                    </div>


                                </div>
                            </div>


                        </div>

          <!-- Project One -->



         <div class="card"  >

                                 <div class="card-header">
                                      <div class="col-lg-6 ">
                                          <strong class="card-title">{{question.description}}</strong></div>
                                           <div class="col-lg-6 ">
                                               <button  class="btn btn-success btn-block">submit</button></div>
 </div>
<div class="card-body">
                 {%for choix in question.free_text_set.all %}
                                        <input type="hidden" value="{{choix.id}}" name="id">
                                      <textarea class="form-control" placeholder="The Text ..." name="text">{{choix.text}}</textarea>
                               {%endfor%} </div>







</form>



          <!-- Pagination -->

        </div>
        <!-- /.container -->
    {% endblock %}

exam/templates/exam/EditMulti.html
    {% extends 'exam/baseProf.html' %}

    {% block title %}Login{% endblock %}

    {% block content %}
        <!-- Page Content -->
        <div class="container">
<form method="post" action="">
          <!-- Page Heading -->

                        <div class="col-xs-12 col-sm-12">
                                 {%csrf_token%}
                            <div class="card">
                                <div class="card-header">
                                    <div class="col-lg-6 ">
                                    <strong>Create Question</strong></div>
                                </div>
                                <div class="card-body card-block">
                                    <div class="form-group">
                                        <label class=" form-control-label">Description: :</label>
                                        <div class="input-group">
                                            <div class="input-group-addon"></div>
                                            <input class="form-control" value="{{question.description}}" name="Description">
                                        </div>
                                        <small class="form-text text-muted"></small>
                                    </div>
                                    <div class="form-group">
                                        <label class=" form-control-label">Header text</label>
                                        <div class="input-group">
                                            <div class="input-group-addon"></div>
                                            <input class="form-control" value="{{question.header_text}}" name="Header_text">
                                        </div>

                                    </div>
                                    <div class="form-group">
                                        <label class=" form-control-label">Footer text</label>
                                        <div class="input-group">
                                            <div class="input-group-addon"></div>
                                            <input class="form-control"value="{{question.footer_text}}" name="Footer_text">
                                        </div>

                                    </div>

                                    <div class="form-group">
                                        <label class=" form-control-label">Success msg</label>
                                        <div class="input-group">
                                            <div class="input-group-addon"></div>
                                            <input class="form-control" value="{{question.success_msg}}" name="Success_msg">
                                        </div>

                                    </div>
                                    <div class="form-group">
                                        <label class=" form-control-label">fail msg</label>
                                        <div class="input-group">
                                            <div class="input-group-addon"></div>
                                            <input class="form-control" value="{{question.fail_msg}}"  name="Fail_msg">
                                        </div>

                                    </div>
                                    <div class="form-group">
                                        <label class=" form-control-label">points</label>
                                        <div class="input-group">
                                            <div class="input-group-addon"></div>
                                            <input class="form-control" type="number" value="{{question.points}}"  name="points">
                                        </div>
                                      
                                    </div>


                                </div>
                            </div>


                        </div>

          <!-- Project One -->



         <div class="card"  >

                                 <div class="card-header">
                                      <div class="col-lg-6 ">
                                          <strong class="card-title">{{question.description}}</strong></div>
                                           <div class="col-lg-6 ">
                                               <button  class="btn btn-success btn-block">submit</button></div>
 </div>
             <div class="card-body">
                            <table class="table">
                              <thead class="thead-dark">
                                <tr>
                                    <th scope="col">#</th>
                                  <th scope="col">answer variant</th>
                                  <th scope="col">answer description</th>
                                  <th scope="col">points</th>
                                </tr>
                              </thead>
                 {%for choix in question.multi_choice_answer_set.all %}
<!--creation d un compteur pour faire le name et l affecter au post-->

                              <tbody>
                                <tr>
                                    <td><input type="hidden" value="{{choix.id}}" name="id{{forloop.counter}}">{{forloop.counter}}</td>
                                  <td><input value="{{choix.multi_variant}}"name="answer_variant{{forloop.counter}}"></td>
                                  <td><input value="{{choix.multi_description}}"name="answer_description{{forloop.counter}}"></td>
                                  <td><input value="{{choix.points}}"name="points{{forloop.counter}}"></td>
                                </tr>

                              </tbody>

{%endfor%}</table>

         </div></div>








</form>



          <!-- Pagination -->

        </div>
        <!-- /.container -->
    {% endblock %}

exam/templates/exam/certif.html
<div style="width:800px; height:600px; padding:20px; text-align:center; border: 10px solid #787878">
<div style="width:750px; height:550px; padding:20px; text-align:center; border: 5px solid #787878">
       <span style="font-size:50px; font-weight:bold">Certificate of Completion</span>
       <br><br>
       <span style="font-size:25px"><i>This is to certify that</i></span>
       <br><br>
       <span style="font-size:30px"><b>{{ username }}</b></span><br/><br/>
       <span style="font-size:25px"><i>has completed the course</i></span> <br/><br/>
       <span style="font-size:30px">{{ examen.name }}</span> <br/><br/>
       <span style="font-size:20px">with score of <b>{{ score }}</b></span> <br/><br/><br/><br/>
       <span style="font-size:25px"><i>dated</i></span><br>

      <span style="font-size:30px">{% now "jS F Y H:i" %} </span>
</div>
</div>

exam/templates/exam/notification.html
{% extends "base.html" %}

{% block title %}Quiz{% endblock %}

{% block content %}


<p>hello</p>
{#<p>{{ notification }}</p>#}
{% endblock %}

exam/templates/exam/passeExam.html
{% extends "base.html" %}

{% block title %}Quiz{% endblock %}

{% block content %}


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        .button {
            border-radius: 4px;
            background-color: #108118;
            border: none;
            color: #FFFFFF;
            text-align: center;
            font-size: 28px;
            padding: 20px;
            width: 200px;
            transition: all 0.5s;
            cursor: pointer;
            margin: 5px;
        }

        .button span {
            cursor: pointer;
            display: inline-block;
            position: relative;
            transition: 0.5s;
        }

        .button span:after {
            content: '\00bb';
            position: absolute;
            opacity: 0;
            top: 0;
            right: -20px;
            transition: 0.5s;
        }

        .button:hover span {
            padding-right: 25px;
        }

        .button:hover span:after {
            opacity: 1;
            right: 0;
        }
    </style>


    <div class="body row">
        <div class="hero-unit col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h4>Exam {{ examen.name }}</h4>
                </div>
                <div class="card-body">


                    <p> r u ready?</p>
                </div>
                <div class="col-lg-4">
                    {% for question in examen.question_set.all %}
                        {% if forloop.counter == 1 %}
                            <a href="{{ question.id }}" class="button"><span>START</span></a>
                        {% endif %}
                    {% endfor %}

                </div>

            </div>
        </div>
        <p id="demo"></p>

    </div>

{% endblock %}

exam/templates/exam/studentIndex.html
{% extends "base.html" %}

{% block title %}Quiz{% endblock %}

{% block content %}




{% endblock %}